create table payang(
DOC_NO	NUMBER not null,
DOC_EMAIL	VARCHAR2(50 BYTE) not null,
DOC_NICK	VARCHAR2(20 BYTE) not null,
DOC_NAME	VARCHAR2(20 BYTE),
DOC_GENDER	VARCHAR2(20 BYTE),
DOC_BIG_NAME	VARCHAR2(20 BYTE),
DOC_KIND	VARCHAR2(20 BYTE),
DOC_AGE	NUMBER,
DOC_SIDO	VARCHAR2(20 BYTE) not null,
DOC_SIGUNGU	VARCHAR2(20 BYTE),
DOC_ADDRESS	VARCHAR2(20 BYTE),
DOC_SUBJECT	VARCHAR2(200 BYTE) not null,
DOC_CONTENT	VARCHAR2(4000 BYTE),
DOC_DATE	DATE,
DOC_UPD_DATE	DATE
);
CREATE TABLE PAYANG_REPLY 
(
  DOC_CNO NUMBER NOT NULL 
, DOC_NO NUMBER NOT NULL 
, DOC_EMAIL VARCHAR2(50) NOT NULL 
, DOC_NICK VARCHAR2(20) 
, DOC_CONTENT VARCHAR2(20) 
, DOC_SECRET CHAR(2) DEFAULT 'N'
, DOC_DATE DATE 
, DOC_UPD_DATE DATE 
, CONSTRAINT MISSING_REPLY_PK PRIMARY KEY 
  (
    DOC_CNO 
  )
  ENABLE 
);

create table missing(
DOC_NO	NUMBER not null,
DOC_EMAIL	VARCHAR2(50 BYTE) not null,
DOC_NICK	VARCHAR2(20 BYTE) not null,
DOC_NAME	VARCHAR2(20 BYTE),
DOC_GENDER	VARCHAR2(20 BYTE),
DOC_BIG_NAME	VARCHAR2(20 BYTE),
DOC_KIND	VARCHAR2(20 BYTE),
DOC_AGE	NUMBER,
DOC_SIDO	VARCHAR2(20 BYTE) not null,
DOC_SIGUNGU	VARCHAR2(20 BYTE),
DOC_ADDRESS	VARCHAR2(20 BYTE),
DOC_SUBJECT	VARCHAR2(200 BYTE) not null,
DOC_CONTENT	VARCHAR2(4000 BYTE),
DOC_DATE	DATE,
DOC_UPD_DATE	DATE
);

CREATE TABLE MISSING_REPLY 
(
  DOC_CNO NUMBER NOT NULL 
, DOC_NO NUMBER NOT NULL 
, DOC_EMAIL VARCHAR2(50) NOT NULL 
, DOC_NICK VARCHAR2(20) 
, DOC_CONTENT VARCHAR2(20) 
, DOC_SECRET CHAR(2) DEFAULT 'N'
, DOC_DATE DATE 
, DOC_UPD_DATE DATE 
, CONSTRAINT MISSING_REPLY_PK PRIMARY KEY 
  (
    DOC_CNO 
  )
  ENABLE 
);

select * from member_list;